# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/german/UnrealEngine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	MarineMonopolist-Android-DebugGame  \
	MarineMonopolist-Android-Development  \
	MarineMonopolist-Android-Shipping  \
	MarineMonopolist-Linux-DebugGame  \
	MarineMonopolist-Linux-Development  \
	MarineMonopolist-Linux-Shipping  \
	MarineMonopolist-LinuxArm64-DebugGame  \
	MarineMonopolist-LinuxArm64-Development  \
	MarineMonopolist-LinuxArm64-Shipping  \
	MarineMonopolist \
	MarineMonopolistEditor-Linux-DebugGame  \
	MarineMonopolistEditor-Linux-Development  \
	MarineMonopolistEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MarineMonopolistEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MarineMonopolistEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

MarineMonopolist-Android-DebugGame:
	 $(BUILD) MarineMonopolist Android DebugGame  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-Android-Development:
	 $(BUILD) MarineMonopolist Android Development  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-Android-Shipping:
	 $(BUILD) MarineMonopolist Android Shipping  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-Linux-DebugGame:
	 $(BUILD) MarineMonopolist Linux DebugGame  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-Linux-Development:
	 $(BUILD) MarineMonopolist Linux Development  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-Linux-Shipping:
	 $(BUILD) MarineMonopolist Linux Shipping  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-LinuxArm64-DebugGame:
	 $(BUILD) MarineMonopolist LinuxArm64 DebugGame  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-LinuxArm64-Development:
	 $(BUILD) MarineMonopolist LinuxArm64 Development  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist-LinuxArm64-Shipping:
	 $(BUILD) MarineMonopolist LinuxArm64 Shipping  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolist: MarineMonopolist-Linux-Development

MarineMonopolistEditor-Linux-DebugGame:
	 $(BUILD) MarineMonopolistEditor Linux DebugGame  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolistEditor-Linux-Development:
	 $(BUILD) MarineMonopolistEditor Linux Development  -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" $(ARGS)

MarineMonopolistEditor: MarineMonopolistEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/german/UnrealProjects/MarineMonopolist/MarineMonopolist.uproject" -Game 

.PHONY: $(TARGETS)
